import Footer from "@/Component/Footer"
import Head from "next/head"
const about = () => {
  return (
    <>
    <Head>
        <title>About Code ajay</title>
        <meta name="description" content="Generated by ajaya"></meta>
    </Head>
    <div>about</div>
    </>
  )
}

export default about
about.getLayout=function pageLayout(page){
    return <>
    {page}
    <Footer/>
    </>
}